# Repository의 Actions 탭에 나타날 Workflow 이름으로 필수 옵션은 아니다.
name: Frontend for CI/CD

# Workflow를 실행시키기 위한 Event 목록
# main 브런치에 대한 변경 사항(push, pull_request)을 감지하면 해당 브런치에 CI Workflow를 실행한다.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  react-deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Repository Resources
        uses: actions/checkout@v4

      #- name: .env 환경 변수 동적 생성
      #  run : |
      #    echo "${{ secrets.CLIENT_ENV }}" > .env
      #    pwd
      #    ls -al

      # .env 설정 아래에 추가
      #- name: nodejs install
      #  uses: actions/setup-node@v4
      #  with:
      #    node-version: '22'

      # node_modules 생성
      - name: npm install
        run: npm install

      # 단위테스트 (추후 진행)
      #- name: 단위테스트
      #  run: npm test

      - name: npm run build
        run: |
          npm run build
          ls ./.next

      - name: 서버(PDSW)에 파일/폴더 업로드
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PDSW_UPDATE_HOST }}
          username: ${{ secrets.PDSW_USER }}
          password: ${{ secrets.PDSW_PASSWORD }}
          port: ${{ secrets.PDSW_PORT }}
          source: "./.next/*, ./public/*"
          target: "/home/nexus/fe_pdsw"

      - name: SSH로 서버(PDSW)에 접속후 서버 재시작
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.PDSW_UPDATE_HOST }}
          username: ${{ secrets.PDSW_USER }}
          password: ${{ secrets.PDSW_PASSWORD }}
          port: ${{ secrets.PDSW_PORT }}
          script_stop: true
          script: |
            cd /home/nexus/fe_pdsw
            npm -v
            npm install
            node env
            pm2 delete fe_pdsw
            # pm2 start ecosystem.config.js --env production
            pm2 start "npx next start" --name fe_pdsw
